version: "3"

services:
  container-disk-debian12-cloud:
    image: au2001/container-disk-debian12-cloud:latest
    build:
      context: ./container-disk-debian12-cloud
      x-bake:
        platforms:
        - linux/amd64
        - linux/arm64

  container-disk-windows11:
    image: au2001/container-disk-windows11:latest
    build:
      context: ./container-disk-windows11
      x-bake:
        platforms:
        - linux/amd64

  container-disk-virtio-win:
    image: au2001/container-disk-virtio-win:latest
    build:
      context: ./container-disk-virtio-win
      x-bake:
        platforms:
        - linux/amd64
